name = "words-pages"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

kv_namespaces = [
  { binding = "VOCABULARY_KV", id = "f61807d323a64c8f871f21b4f3840a34" }
]
