name = "words-pages"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

kv_namespaces = [
  { binding = "VOCABULARY_KV", id = "78133d37f1734ec59068b9e2a3fdca84" }
]
